services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: on-failure
    command:
      - --config.file=/etc/prometheus-config/prometheus.yaml
    volumes:
      - ./config/prometheus:/etc/prometheus-config
    ports:
      - '9090:9090'

  mimir:
    container_name: mimir
    image: grafana/mimir:latest
    restart: on-failure
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ./config/mimir:/etc/mimir-config
    ports:
      - '9009:9009'
    depends_on:
      - prometheus

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: on-failure
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    depends_on:
      - prometheus
