services:
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    restart: on-failure
    command:
      - -config.file=/etc/tempo-config/tempo.yaml
    volumes:
      - ./config/tempo:/etc/tempo-config
    ports:
      - '3200:3200'
      - '4317:4317'
      - '4318:4318'
    depends_on:
      - loki
      - mimir
      - pyroscope

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: on-failure
    ports:
      - '3100:3100'

  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:latest
    restart: on-failure
    ports:
      - '4040:4040'
