services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: on-failure
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana-config
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '4000:3000' # Changed to map host port 4000 to container port 3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
      interval: 1s
      start_interval: 0s
      timeout: 10s
      retries: 5
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_COOKIE_SAMESITE=none

  install-dashboard-dependencies:
    container_name: install-dashboard-dependencies
    build: images/jb
    restart: 'no'
    depends_on:
      grafana:
        condition: service_healthy
    volumes:
      - ./operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: jb install

  # Provision alloy-mixin after Grafana is healthy and running.
  provision-dashboards:
    container_name: provision-dashboards
    build: images/grizzly
    restart: 'no'
    depends_on:
      install-dashboard-dependencies:
        condition: service_completed_successfully
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: grr apply grizzly/dashboards.jsonnet

  # Watch dashboards for changes and apply them to Grafana.
  watch-dashboards:
    container_name: watch-dashboards
    build: images/grizzly
    restart: on-failure
    depends_on:
      install-dashboard-dependencies:
        condition: service_completed_successfully
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: grr watch dashboards/ grizzly/dashboards.jsonnet
